### ISSUE TITLE
1.18.2 - JEI 兼容问题导致查看合成表时客户端崩溃

### ISSUE THREAD

**Issue by NattoCB** [FierceManul/BlackHoleStorage#2]
**环境**
minecraft: 1.18.2
forge: 40.2.0

**描述这个BUG**

从黑洞控制面板进入 UI，选择一条渠道进入存储界面（大箱子UI）

使用JEI查看物品合成方式（按R或U）导致客户端崩溃

**导致的问题**

客户端崩溃，无法从黑洞UI查看合成表

**复现方法**

步骤如上所属

**日志**
```java
java.lang.NullPointerException: Cannot invoke "java.lang.Class.isAssignableFrom(java.lang.Class)" because the return value of "mezz.jei.api.recipe.transfer.IRecipeTransferHandler.getRecipeClass()" is null
	at mezz.jei.common.recipes.RecipeTransferManager.getHandler(RecipeTransferManager.java:41) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.recipes.RecipeTransferManager.getRecipeTransferHandler(RecipeTransferManager.java:33) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005] 
	at mezz.jei.common.gui.recipes.RecipeGuiLogic.getRecipeCategoryIndexToShowFirst(RecipeGuiLogic.java:87) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:69) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005] 
	at mezz.jei.common.gui.recipes.RecipesGui.show(RecipesGui.java:442) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.input.handlers.FocusInputHandler.lambda$handleShow$1(FocusInputHandler.java:46) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at mezz.jei.common.input.handlers.FocusInputHandler.handleShow(FocusInputHandler.java:41) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.input.handlers.FocusInputHandler.handleUserInput(FocusInputHandler.java:28) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.input.handlers.CombinedInputHandler.handleClickInternal(CombinedInputHandler.java:86) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005] 
	at mezz.jei.common.input.handlers.CombinedInputHandler.handleImmediateClick(CombinedInputHandler.java:47) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.input.handlers.CombinedInputHandler.handleUserInput(CombinedInputHandler.java:33) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.common.input.ClientInputHandler.onKeyboardKeyPressedPre(ClientInputHandler.java:31) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.forge.startup.EventRegistration.lambda$registerClientInputHandler$1(EventRegistration.java:33) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at mezz.jei.core.util.WeakConsumer.accept(WeakConsumer.java:17) ~[%5Bc%5Djei-1.18.2-forge-10.2.1.1005.jar%2364!/:10.2.1.1005]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.client.ForgeHooksClient.onScreenKeyPressedPre(ForgeHooksClient.java:681) ~[forge-1.18.2-40.2.10-universal.jar%23191!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:362) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:353) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:452) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:451) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2345!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2349!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23186!/:?] 
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by FierceManul** [comment]
你换个jei版本试试，他改过api的。
