### ISSUE TITLE
1.18.2 - 服务器启动后崩溃

### ISSUE THREAD

**Issue by NattoCB** [FierceManul/BlackHoleStorage#7]
## 背景

版本：1.18.2

在服务器上运行了一两个月，近期开始突然会在启动时直接崩溃

## 错误报告

```java
[16:51:02] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus]: Exception caught during firing event: 黑洞储存在加载数据的时候出错了！ 本次游戏将不会保存数据！
	Index: 7
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@3460e5e4
		4: ASM: com.finallion.villagersplus.VillagersPlus@810dc03 onServerAboutToStartEvent(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@43bf0cd5
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@7271b1cb
		7: ASM: class com.fiercemanul.blackholestorage.channel.ServerChannelManager onServerLoad(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		8: ASM: class noobanidus.mods.lootr.event.HandleChunk onServerStarted(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@42c34485
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@71bfd6fc
		11: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@4a5db5ba
		12: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@35ddbad3
		13: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@6de22781
		14: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@62e514f7
		15: net.minecraftforge.eventbus.EventBus$$Lambda$1442/0x0000000801275cd8@45328d74
		16: ASM: class com.elfmcys.yesstevemodel.Oo0O0oo0Oo00OoooOOoOoO0O OooOo0oOoOO0o00OO000oO00(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		17: ASM: top.theillusivec4.champions.common.ChampionEventsHandler@2f015a4b onServerStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		18: ASM: mods.flammpfeil.slashblade.event.AllowFlightOverrwrite@2f45c334 onFMLServerAboutToStartEvent(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		19: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@54172169 serverAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
		20: LOWEST
		21: ASM: class com.github.alexthe666.iceandfire.IceAndFire onServerAboutToStart(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
java.lang.RuntimeException: 黑洞储存在加载数据的时候出错了！ 本次游戏将不会保存数据！
	at TRANSFORMER/blackholestorage@1.0.1-Snapshot-1.18.2/com.fiercemanul.blackholestorage.channel.ServerChannelManager.load(ServerChannelManager.java:148)
	at TRANSFORMER/blackholestorage@1.0.1-Snapshot-1.18.2/com.fiercemanul.blackholestorage.channel.ServerChannelManager.<init>(ServerChannelManager.java:109)
	at TRANSFORMER/blackholestorage@1.0.1-Snapshot-1.18.2/com.fiercemanul.blackholestorage.channel.ServerChannelManager.newInstance(ServerChannelManager.java:52)
	at TRANSFORMER/blackholestorage@1.0.1-Snapshot-1.18.2/com.fiercemanul.blackholestorage.channel.ServerChannelManager.onServerLoad(ServerChannelManager.java:59)
	at net.minecraftforge.eventbus.ASMEventHandler_325_ServerChannelManager_onServerLoad_ServerAboutToStartEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.18/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:86)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:238)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:945)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:344)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.nbt.NbtIo.m_202493_(NbtIo.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.nbt.NbtIo.m_128939_(NbtIo.java:48)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.nbt.NbtIo.m_128937_(NbtIo.java:28)
	at TRANSFORMER/blackholestorage@1.0.1-Snapshot-1.18.2/com.fiercemanul.blackholestorage.channel.ServerChannelManager.load(ServerChannelManager.java:135)
	... 12 more

```

**Comment by FierceManul** [comment]
你确定你的存档还好着吗

**Comment by NattoCB** [comment]
> 你确定你的存档还好着吗

感觉是加载到了什么不合法的 NBT，我周末调试看看

**Comment by NattoCB** [comment]
排查发现是不知何时产生了一个全空的dat
![image](https://github.com/user-attachments/assets/523b87c9-b724-4c23-b33f-0f39ded0a1cd)
![image](https://github.com/user-attachments/assets/592054d3-f9f5-4bb4-b95f-a937c8579e96)
但对应那天的日志并没有报错输出
